name: Publish Workflow CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} and clone repo
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Bump Version
        run: npm version patch

      - name: Commit and Push Version
        run: |
          git config user.email "pinoyfreecoder@gmail.com"
          git config user.name "PinoyFreeCoder"
          git add package.json
          git commit -m "Bump version"
          git push

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
